apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  namespace: config
  labels:
    app: config
spec:
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: phunguyen9297/config:0.0.5
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_NAME
              value: application
            - name: SPRING_CONFIG_LOCATION
              value: /app/config/
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: config
      nodeSelector:
        kubernetes.io/arch: "amd64"
---
apiVersion: v1
kind: Service
metadata:
  name: config
  namespace: config
spec:
  selector:
    app: config
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
