#apiVersion: v1
#kind: Service
#metadata:
#  name: config
#  namespace: config
#spec:
#  selector:
#    app: config
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8080
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: config
#  namespace: default
#  annotations:
#    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
#spec:
#  rules:
#    - host: config.phu.homes
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: config
#                port:
#                  number: 80
